### ISSUE TITLE
Wiring diagram in tutorial

### ISSUE THREAD

**Issue by CrisAdam** [kyesh/ArduinoTutorial#1]
![img](http://content.screencast.com/users/slapshot136/folders/Jing/media/870c6e5f-8c53-408a-909f-f8bac8472bb2/2016-02-13_1448.png)

having 2 ground wires is not needed and makes it more cluttered than necessary

**Comment by kyesh** [comment]
lol, didn't see this...

But they need to share a common ground. Your using the battery as the
supply for the Arduino so it is inherently done for you

**Comment by CrisAdam** [comment]
I don't think we are talking about the same ground:

![img](http://content.screencast.com/users/slapshot136/folders/Jing/media/fda71cf8-8bd7-4729-9dcd-600544ae821b/2016-02-20_1326.png)

it's just that on an actual breadboard it creates more jumper wire clutter than necessary

**Comment by kyesh** [comment]
Oh sorry, yeah but it allows the current to be distributed through more 
wires. I.E. less chance to burn out the IC. Probably not necessary for 
the power our motors are using but I'd rather be safe than sorry

**Comment by CrisAdam** [comment]
not sure distributing current helps.. it's the same current as what comes in the 9v pin essentially (the chip doesn't really use that much itself..)
